title: "我的博客"
description: "一个简洁的个人博客"
url: "https://champeil.github.io"
author: "你的名字"
timezone: Asia/Shanghai
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/page:num"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
collections:
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
