# 基本设置
title: Your Site Title
description: Your site description
baseurl: "" # 如果是 username.github.io 则留空
url: "https://champeil.github.io" # 您的实际 URL

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
