# _config.yml - Jekyll主配置文件
title: 我的博客
description: 分享技术与生活的点点滴滴
baseurl: ""
url: "https://yourusername.github.io" # 替换为你的GitHub Pages地址

# 作者信息
author:
name: Your Name
email: your.email@example.com
github: yourusername
twitter: yourusername

# 构建设置
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# 集合设置
collections:
posts:
  output: true
  permalink: /:categories/:year/:month/:day/:title/

# 默认设置
defaults:
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
    comments: true
- scope:
    path: ""
    type: "pages"
  values:
    layout: "page"

# 排除文件
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/

# 时区设置
timezone: Asia/Shanghai

# 语言设置
lang: zh-CN

---
# Gemfile - Ruby依赖文件
source "https://rubygems.org"

gem "jekyll", "~> 4.3.0"
gem "minima", "~> 2.5"

group :jekyll_plugins do
gem "jekyll-feed", "~> 0.12"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-paginate"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
gem "tzinfo", ">= 1", "< 3"
gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

---
# index.html - 首页文件
---
layout: default
---

<div class="home">
<h1 class="page-heading">最新文章</h1>

<div class="post-list">
  {% for post in site.posts limit:10 %}
    <article class="post-item">
      <h2 class="post-title">
        <a href="{{ post.url | relative_url }}">{{ post.title | escape }}</a>
      </h2>
      
      <div class="post-meta">
        <time datetime="{{ post.date | date_to_xmlschema }}">
          {{ post.date | date: "%Y年%m月%d日" }}
        </time>
        {% if post.author %}
          <span class="author">by {{ post.author }}</span>
        {% endif %}
      </div>
      
      <div class="post-excerpt">
        {{ post.excerpt | strip_html | truncatewords: 50 }}
      </div>
      
      {% if post.tags.size > 0 %}
        <div class="post-tags">
          {% for tag in post.tags %}
            <span class="tag">{{ tag }}</span>
          {% endfor %}
        </div>
      {% endif %}
    </article>
  {% endfor %}
</div>

<div class="pagination">
  {% if paginator.previous_page %}
    <a href="{{ paginator.previous_page_path }}" class="prev">上一页</a>
  {% endif %}
  
  {% if paginator.next_page %}
    <a href="{{ paginator.next_page_path }}" class="next">下一页</a>
  {% endif %}
</div>
</div>
