# 站点设置
title: 我的个人博客
email: your-email@example.com
description: >-
  欢迎来到我的个人博客，这里记录着我的技术心得和生活感悟。
baseurl: "" # 如果你的博客不在域名根目录，需要设置这个
url: "https://yourusername.github.io" # 你的站点URL
github_username: yourusername
twitter_username: yourusername

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Google Analytics
google_analytics: UA-XXXXXXXXX-X

# 文章链接格式
permalink: /:year/:month/:day/:title/

# 分页
paginate: 10
paginate_path: "/page:num/"

# 默认值
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "你的名字"

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
