title: "我的博客"
description: "一个简洁的个人博客"
url: "https://champeil.github.io/"
author: "你的名字"
timezone: Asia/Shanghai
markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:day/:title/
plugins: []   # 不使用自定义插件，保证 GitHub Pages 兼容
collections:
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
