# 站点设置
title: 啊哈！
email: laojp@sysucc.org.cn
description: >-
  哦哦~做到只积咁嘅样~
baseurl: "" # 如果你的博客不在域名根目录，需要设置这个
url: "https://champeil.github.io" # 你的站点URL
github_username: champeil

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Google Analytics
google_analytics: UA-XXXXXXXXX-X

# 文章链接格式
permalink: /:year/:month/:day/:title/

# 分页（注意：需要添加 jekyll-paginate 插件）
# paginate: 10
# paginate_path: "/page:num/"

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
